### ISSUE TITLE
sed: can't read discourse.conf: No such file or directory

### ISSUE THREAD

**Issue by Gyvastis** [pl3bs/dontdockmebro#1]
It's accuring when I'm entering user data (host, email, api key, etc.). 
I think it's `line 91` in the `install.sh` - there is no `discourse_quickstart.conf` in that folder

BTW, it's missing info of how to check if Discourse is online already and working or not.

**Comment by pl3bs** [comment]
discourse_quickstart is in the discourse main folder.

you can check discourse status via:

service disc status

or looking at running processes

edit:

quickstart has been removed, attempted to modify with current config file, plz let me know if this works.

**Comment by Gyvastis** [comment]
Yep, it did the trick - passed through OK :)

edit:

Could you tell me how to point a domain to Discourse? I've pointed the domain to VPS IP but nothing good shows up.

**Comment by pl3bs** [comment]
good to hear xD

you need an a-record pointing to that IP. 

check whatsmydns.net, enter in your domain name, and verify that it is properly pointing to that location. 

you can also use ping, nslookup for this in the terminal. 

if everything is properly setup, it should show. 

try the:

service disc status, or 

service disc restart

**Comment by Gyvastis** [comment]
And I need to edit `/etc/nginx/conf.d/disco.conf`? Sorry, first time with `nginx`

**Comment by pl3bs** [comment]
are you running anything else on the VPS? the guide is meant for fresh installs with no other sites. if it's the only thing you're running, no need to mess with the config file in nginx.
