### ISSUE TITLE
URGENT: FATAL:  database "discourse" does not exist

### ISSUE THREAD

**Issue by ghost** [pl3bs/dontdockmebro#3]
```
URGENT: FATAL:  database "discourse" does not exist
Run `$ bin/rake db:create db:migrate` to create your database Failed to initialize site default
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "discourse" does not exist
Run `$ bin/rake db:create db:migrate` to create your database
```

I get this error when I try to run install.sh. I created the database using psql, but when I try running `RUBY_GC_MALLOC_LIMIT=90000000 RAILS_ENV=production bundle exec rake db:migrate` in /var/www/discourse, it says `bash: bundle: command not found`

**Comment by pl3bs** [comment]
I'm not sure what you're doing, but the db is created on line 109. you must be deviating from the script in some way.

**Comment by ghost** [comment]
Nope, I just cloned the script and ran it. I'm not using OVH though. Does
it have to do with that?

**Comment by pl3bs** [comment]
try it now, I see the new config file has "discourse" instead of "discourse_prod", so changed that. 

bundle must be run with the correct user to show, else that error occurs. if the script installs successfully, you should be able to startup discourse with:

service disc start
